const images = {
  sidenavIcon: require('../assets/img/sidenav.png'),
  dashboardFlashIcon: require('../assets/img/icon_flash_dashboard.png'),
  dashboardIcon: require('../assets/img/icn_dashboard.png'),
  visitIcon: require('../assets/img/icn_visit.png'),
  visitflashIcon: require('../assets/img/icn_visit_flash.png'),
  remarksIcon: require('../assets/img/icn_my_remarks.png'),
  profileIcon: require('../assets/img/icn_profile.png'),
  settingsIcon: require('../assets/img/icn_settings.png'),
  logoutIcon: require('../assets/img/icn_logout.png'),
  splashSLogo: require('../assets/img/logo_splash.png'),
  eiffageLogo: require('../assets/img/logo_eiffage.png'),
  splashSquares: require('../assets/img/img_squares_splash.png'),
  filterHiglitedIcon: require('../assets/img/icn_filter_highlighted.png'),
  filterArrowIcon: require('../assets/img/icn_filter_arrow.png'),
  infoIcon: require('../assets/img/icn_info.png'),
  textareaIcon: require('../assets/img/icn_textarea.png'),
  dividerIcon: require('../assets/img/Divider.png'),
  takePhotoIcon: require('../assets/img/icn_prendre_photo.png'),
  fileIcon: require('../assets/img/icn_file.png'),
  NegDisabledIcon: require('../assets/img/icn_negative_disabled.png'),
  PositDisabledIcon: require('../assets/img/icn_positive_disabled_blocked.png'),
  searchIcon: require('../assets/img/icn_search.png'),
  inputIcon: require('../assets/img/icon_saisie.png'),
  constructionIcon: require('../assets/img/icon_chantier.png'),
  qrCodeIcon: require('../assets/img/icon_qr_code.png'),
  addPrevenationIcon: require('../assets/img/icn_add_prevention.png'),
  addConformite: require('../assets/img/icn_add_conformite.png'),
  addhierarchicalIcon: require('../assets/img/icn_add_hierarchique.png'),
};
export default images;
