export const TRANSLATE = {
  CHANTIERS: 'txt.chantiers',
  MY_CHANTIERS: 'txt.mes.chantier',
  AUTRES_CHANTIERS: 'txt.autres.chantier',
  REFERNTIEL_LISTES: 'txt.referentiel.listes',
  RISQUES_QUESTIONS: 'txt.typology.risques.questions',
  PHOTOS: 'txt.photos',
  NO_PHOTOS: 'txt.no.photos.wait.send',
  LANGUAGE: 'txt.language',
  ABOUT: 'settings_about',
  CONFIDENTIALITY: 'settings_confidentiality',
  LEGAL_NOTICE: 'settings_legal_notice',
  LAST_UPDATE: 'txt.last.update.at',
  SETTINGS: 'txt.settings',
  PROFILE: 'txt.profile',
  REMARKS: 'txt.my.remarks',
  VISIT_FLASH: 'txt.new.visit.flash',
  VISITS: 'txt.visites',
  DASHBOARD: 'txt.dashboard',
};
